<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Forgot Password_1</name>
   <tag></tag>
   <elementGuidId>591d8dad-76f8-4c26-ac5e-63d712fff01f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auth-fpp-link-bottom</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='auth-fpp-link-bottom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dd993a95-91c0-42b2-bfa2-c9bba3bce7a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth-fpp-link-bottom</value>
      <webElementGuid>6af9a946-3854-4a6d-96ae-a490ab2755cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-link-normal</value>
      <webElementGuid>2d1e33a5-41a1-4976-8be1-192acbf7e819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>0e125ab9-ad65-40d7-b040-f6fdd7a4865d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.amazon.in/ap/forgotpassword?useMobileAsClaim=true&amp;showRememberMe=true&amp;openid.pape.max_auth_age=0&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;signInRedirectToFPPThreshold=5&amp;showMessageRatesApply=false&amp;pageId=inflex&amp;showSignInWithOTPButton=true&amp;openid.return_to=https%3A%2F%2Fwww.amazon.in%2F%3Fref_%3Dnav_custrec_signin&amp;prevRID=5229VG97D9WENFNTE891&amp;openid.assoc_handle=inflex&amp;useSignInWithOTP=true&amp;openid.mode=checkid_setup&amp;prepopulatedLoginId=eyJjaXBoZXIiOiJmTTlHNGVlVlF6c3lsS0I5T2NkTTdnPT0iLCJJViI6IlN4aVAzYzd2ektHU1RUWkVqZTJYSmc9PSIsInZlcnNpb24iOjF9&amp;failedSignInCount=0&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;timestamp=1705687423000</value>
      <webElementGuid>bd7a8bb0-8ba2-43b1-a35c-a167a5a3dbd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Forgot Password
</value>
      <webElementGuid>14a04678-1875-42b5-ab58-218b23e98a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-fpp-link-bottom&quot;)</value>
      <webElementGuid>39f3df3b-d769-4b5f-a08e-a5814495056e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='auth-fpp-link-bottom']</value>
      <webElementGuid>03278fe1-ebe3-4ad8-be4a-ca977b26aca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='authportal-main-section']/div[2]/div/div[2]/div/form/div/div/div/div[2]/a</value>
      <webElementGuid>b46f53d0-d9d0-4fcc-a003-261c0de50100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Forgot Password')]</value>
      <webElementGuid>7b55d00f-80e5-4265-83bd-4e9b2072442e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.amazon.in/ap/forgotpassword?useMobileAsClaim=true&amp;showRememberMe=true&amp;openid.pape.max_auth_age=0&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;signInRedirectToFPPThreshold=5&amp;showMessageRatesApply=false&amp;pageId=inflex&amp;showSignInWithOTPButton=true&amp;openid.return_to=https%3A%2F%2Fwww.amazon.in%2F%3Fref_%3Dnav_custrec_signin&amp;prevRID=5229VG97D9WENFNTE891&amp;openid.assoc_handle=inflex&amp;useSignInWithOTP=true&amp;openid.mode=checkid_setup&amp;prepopulatedLoginId=eyJjaXBoZXIiOiJmTTlHNGVlVlF6c3lsS0I5T2NkTTdnPT0iLCJJViI6IlN4aVAzYzd2ektHU1RUWkVqZTJYSmc9PSIsInZlcnNpb24iOjF9&amp;failedSignInCount=0&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;timestamp=1705687423000')]</value>
      <webElementGuid>5a81e81b-fb3a-49da-883b-cfd8fd559b8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>a1fe8483-9b39-431f-bd64-f642dded306e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'auth-fpp-link-bottom' and @href = 'https://www.amazon.in/ap/forgotpassword?useMobileAsClaim=true&amp;showRememberMe=true&amp;openid.pape.max_auth_age=0&amp;openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;signInRedirectToFPPThreshold=5&amp;showMessageRatesApply=false&amp;pageId=inflex&amp;showSignInWithOTPButton=true&amp;openid.return_to=https%3A%2F%2Fwww.amazon.in%2F%3Fref_%3Dnav_custrec_signin&amp;prevRID=5229VG97D9WENFNTE891&amp;openid.assoc_handle=inflex&amp;useSignInWithOTP=true&amp;openid.mode=checkid_setup&amp;prepopulatedLoginId=eyJjaXBoZXIiOiJmTTlHNGVlVlF6c3lsS0I5T2NkTTdnPT0iLCJJViI6IlN4aVAzYzd2ektHU1RUWkVqZTJYSmc9PSIsInZlcnNpb24iOjF9&amp;failedSignInCount=0&amp;openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&amp;openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&amp;timestamp=1705687423000' and (text() = '
  Forgot Password
' or . = '
  Forgot Password
')]</value>
      <webElementGuid>b0bf3433-6aaa-46db-a06b-b89d90cda73c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
