<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Best Sellers</name>
   <tag></tag>
   <elementGuidId>81ae41dc-a3a8-423a-86f5-3fae69137575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-content']/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.hmenu-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>24af68ed-c8af-4766-88af-2d907cc32c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gp/bestsellers/?ref_=nav_em_cs_bestsellers_0_1_1_2</value>
      <webElementGuid>8c0970a7-fddd-47e1-8e90-6a6ca8ea26aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmenu-item</value>
      <webElementGuid>7212d17c-cef6-4c5b-a8cb-b3af472b97e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Best Sellers</value>
      <webElementGuid>5ea20a92-56da-4a0c-8717-667ed2675981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-content&quot;)/ul[@class=&quot;hmenu hmenu-visible&quot;]/li[2]/a[@class=&quot;hmenu-item&quot;]</value>
      <webElementGuid>a955e202-ad75-4776-af9b-17e611ba92ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-content']/ul/li[2]/a</value>
      <webElementGuid>f822e9f8-a687-449d-a74c-620bdbfac656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Best Sellers')])[2]</value>
      <webElementGuid>bde2ecb8-7177-4e44-a184-57f6ecc1ef35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gp/bestsellers/?ref_=nav_em_cs_bestsellers_0_1_1_2')]</value>
      <webElementGuid>e2871ce1-1c7e-4059-b411-947849a30108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[2]/a</value>
      <webElementGuid>b58fcb37-f57a-4b39-bceb-aefbeb47bdbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gp/bestsellers/?ref_=nav_em_cs_bestsellers_0_1_1_2' and (text() = 'Best Sellers' or . = 'Best Sellers')]</value>
      <webElementGuid>6a4a6969-851b-4f73-9cd2-8c6e1eb40ab9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
