<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Enter the email youd like to use for y_1825da</name>
   <tag></tag>
   <elementGuidId>2d6af144-d5ac-4e52-b211-64290f69e929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#landingFormId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='landingFormId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>90db802c-a328-4df4-acdd-74f1c6692a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b-form b-text-base b-mt-medium</value>
      <webElementGuid>bc35c228-a95a-4327-9636-3ad77de8490c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>landingFormId</value>
      <webElementGuid>2bb5c91f-9c66-4c58-9734-84e3acecba71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter the email you'd like to use for your business accountGet started</value>
      <webElementGuid>33ff0d59-2416-4608-99cb-eb21f44fae7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landingFormId&quot;)</value>
      <webElementGuid>e271a638-0fae-4979-ae3e-25f71b669bb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//form[@id='landingFormId']</value>
      <webElementGuid>1841c688-924d-4488-baa9-127c169e4cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div/div/form</value>
      <webElementGuid>1ef87c8e-46bc-4ab2-9cd0-221d6efb0a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>7dab862a-5a0e-40bb-a043-7e29558e27fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[@id = 'landingFormId' and (text() = concat(&quot;Enter the email you&quot; , &quot;'&quot; , &quot;d like to use for your business accountGet started&quot;) or . = concat(&quot;Enter the email you&quot; , &quot;'&quot; , &quot;d like to use for your business accountGet started&quot;))]</value>
      <webElementGuid>72680e2c-1eb2-4bed-a6ca-54a83209564c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
