<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_businessEmail</name>
   <tag></tag>
   <elementGuidId>f7c65fa8-3d3e-47ef-8a85-2d0c079f308f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#businessEmail-field-id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='businessEmail-field-id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cb777d88-8f74-4901-af56-0b0734869f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>businessEmail-field-id</value>
      <webElementGuid>e81ffde8-f339-4546-b709-081c63867cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b-form-control</value>
      <webElementGuid>70f32cf3-df32-47b4-b5f5-1b85e26bea61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98e10318-957f-45fd-871e-02d007e4dcbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>businessEmail-test-id</value>
      <webElementGuid>06118186-7501-434a-a3ff-60192f3b5486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>businessEmail-field-label-id</value>
      <webElementGuid>abdf284b-bb0b-44fe-a886-789de3bbc453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>businessEmail</value>
      <webElementGuid>5c5c0414-1ec9-48fb-ad5a-369749dfb4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>businessEmail-field-label-id</value>
      <webElementGuid>56e71c77-acbd-4142-a3ff-ee38eca7c65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter email address</value>
      <webElementGuid>11d6fb8b-8217-4f62-8b3d-325e03fb09a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>411ba24c-89bd-4efa-8b83-ba1b8bddda10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>e95b061f-7a99-49b8-ae33-e87254fe59be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>845c211b-1237-42e7-9a13-ff196be4da5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;businessEmail-field-id&quot;)</value>
      <webElementGuid>af8863c0-43ee-4f32-96e9-9111eae32537</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='businessEmail-field-id']</value>
      <webElementGuid>82a80f0c-3ccf-4785-83dc-6ded86e17d53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='landingFormId']/fieldset/input</value>
      <webElementGuid>1cca82b6-b327-4194-adfd-f2629ad5cf7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>37bf6c74-237b-4e49-864f-698128c8aefb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'businessEmail-field-id' and @type = 'text' and @name = 'businessEmail' and @placeholder = 'Enter email address']</value>
      <webElementGuid>0f94f781-8e6d-4ce5-8fc8-e33db817cf29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
