<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Get started</name>
   <tag></tag>
   <elementGuidId>0c97f53a-391a-431e-b067-1c98f171906f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submitEmailButtonId > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submitEmailButtonId']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a808230a-271a-46cc-b661-ad3a25bdcff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get started</value>
      <webElementGuid>78198726-b908-4b13-8388-b2c0af5219eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitEmailButtonId&quot;)/span[1]</value>
      <webElementGuid>2da95e3b-753f-413e-8310-e175660182b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='submitEmailButtonId']/span</value>
      <webElementGuid>9fb61f42-4bcb-401e-9552-6f09ac856ccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>68c571d8-460c-403a-a447-868927571866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Get started' or . = 'Get started')]</value>
      <webElementGuid>3a8707a9-d8c7-4822-919c-4dc35ca958a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
