<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_submit.buy-now</name>
   <tag></tag>
   <elementGuidId>c3cf88ef-e901-4c05-b1d8-f4013e5b97e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buy-now-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buy-now-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>14a1d8de-0f56-4ea5-a2bd-4510d46a50ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buy-now-button</value>
      <webElementGuid>9ff44c6c-3cbe-4f1e-ad1d-044733bd924c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>submit.buy-now</value>
      <webElementGuid>44fdd531-5f9e-4317-bb2b-8913ba7a253f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Buy Now</value>
      <webElementGuid>f49f7532-8d10-43bf-997d-b7de4d902ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-hover</name>
      <type>Main</type>
      <value>Select &lt;b>__dims__&lt;/b> from the left&lt;br> to Buy</value>
      <webElementGuid>a7f6b54a-b930-4600-92c8-6f33a294d41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>d62af41b-2fd2-4997-8160-1aa2ec2f4f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9bfe2b13-bb97-4094-9e73-223fd86cc568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>submit.buy-now-announce</value>
      <webElementGuid>7f485439-74fe-4071-a3ac-f4ea6f9514b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buy-now-button&quot;)</value>
      <webElementGuid>249a309c-d269-4c50-8186-2676ebb931a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buy-now-button']</value>
      <webElementGuid>50fbf691-5c1f-4d54-a819-a2e75b04147d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='submit.buy-now']/span/input</value>
      <webElementGuid>b5184cee-2188-4d10-9058-63c917c12de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[39]/div/div/span/span/input</value>
      <webElementGuid>7ccb057f-4989-43fa-b8bc-96d8acecdcc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'buy-now-button' and @name = 'submit.buy-now' and @title = 'Buy Now' and @type = 'submit']</value>
      <webElementGuid>9eb880eb-d8ea-4dbb-9a51-eac2538f1ed8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
