<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please make a selection I forgot my _d18bd3</name>
   <tag></tag>
   <elementGuidId>1bf16b4e-8799-4ef1-bdfe-658256beb618</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cu-select-firstNode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cu-select-firstNode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>45133647-0037-4d8e-9350-63a3069a8403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cu-select-firstNode</value>
      <webElementGuid>72ef2b83-21f1-4090-bf02-9d3b9dbbbe90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt; Please make a selection >I forgot my passwordI cannot sign into my accountI do not have an Amazon account but need assistanceI cannot create an accountMy account is on hold</value>
      <webElementGuid>43777d92-0444-4894-8381-e5747f7a7a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cu-select-firstNode&quot;)</value>
      <webElementGuid>074b3b4a-e251-4e8b-878e-d268c49ddf57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cu-select-firstNode']</value>
      <webElementGuid>4700de7c-7837-47d7-b171-6606bc544844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cu-ism-firstNode']/div[2]/select</value>
      <webElementGuid>dccf7890-fef9-407e-915d-78136a2dc223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>32637f45-2ebc-406b-b5ac-cacbc4866ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'cu-select-firstNode' and (text() = '&lt; Please make a selection >I forgot my passwordI cannot sign into my accountI do not have an Amazon account but need assistanceI cannot create an accountMy account is on hold' or . = '&lt; Please make a selection >I forgot my passwordI cannot sign into my accountI do not have an Amazon account but need assistanceI cannot create an accountMy account is on hold')]</value>
      <webElementGuid>de64c598-6eb9-48b4-baf1-64779c8b1885</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
