<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Customer Service</name>
   <tag></tag>
   <elementGuidId>cddc7281-3125-4489-bae6-db0d436b0eb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-content']/ul/li[30]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(30) > a.hmenu-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a6bb2ed9-049e-4fc6-9db9-67aef4685fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gp/help/customer/display.html?nodeId=508510&amp;ref_=nav_em_cs_help_0_1_1_36</value>
      <webElementGuid>f34211fd-f6e9-4955-b013-af0bda082205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmenu-item</value>
      <webElementGuid>9183b0f4-48c3-42b4-b072-99463ecea315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer Service</value>
      <webElementGuid>cefdfe1a-8124-4038-a06d-03d0f042490d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-content&quot;)/ul[@class=&quot;hmenu hmenu-visible&quot;]/li[30]/a[@class=&quot;hmenu-item&quot;]</value>
      <webElementGuid>905337c9-c24e-47d2-b0a2-2dc9b9aea998</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-content']/ul/li[30]/a</value>
      <webElementGuid>c2107af7-0c3e-431f-9cf7-bce98cb2847b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Customer Service')])[2]</value>
      <webElementGuid>08406a59-5b88-4e4b-8d05-93a2d781856f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gp/help/customer/display.html?nodeId=508510&amp;ref_=nav_em_cs_help_0_1_1_36')]</value>
      <webElementGuid>5f5c24af-6058-43d6-ae03-aaa7fdf4925a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[30]/a</value>
      <webElementGuid>f05ed816-fba4-4bdd-9e0c-8d25fefe8028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gp/help/customer/display.html?nodeId=508510&amp;ref_=nav_em_cs_help_0_1_1_36' and (text() = 'Customer Service' or . = 'Customer Service')]</value>
      <webElementGuid>8d023fff-e89a-44aa-a647-2613f6e37885</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-content']/ul/li[31]/a</value>
      <webElementGuid>b0e8b1eb-3ab7-42a6-b00d-0910d0516e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gp/help/customer/display.html?nodeId=508510&amp;ref_=nav_em_cs_help_0_1_1_37')]</value>
      <webElementGuid>ef60f663-e94d-49b1-a878-2bcb7dc5af7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[31]/a</value>
      <webElementGuid>a86337ce-6775-4428-bf8b-e7e60effd884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gp/help/customer/display.html?nodeId=508510&amp;ref_=nav_em_cs_help_0_1_1_37' and (text() = 'Customer Service' or . = 'Customer Service')]</value>
      <webElementGuid>3f8f8c0c-71f4-47b8-9984-a6c31ef73a90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
