<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divhmenu-canvas-background</name>
   <tag></tag>
   <elementGuidId>9082940d-8152-48f8-9238-b34a43bf96a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-canvas-background']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hmenu-canvas-background</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a018379-fcf5-4bd4-87d5-6acf80a17207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hmenu-canvas-background</value>
      <webElementGuid>e4e6537f-0d80-46c8-834c-662eca532e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmenu-dark-bkg-color hmenu-opaque</value>
      <webElementGuid>8cde8c77-1606-44cc-8fe7-9f3381999bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-canvas-background&quot;)</value>
      <webElementGuid>5e625bb5-654a-4546-a0c9-07d3680d75f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='hmenu-canvas-background']</value>
      <webElementGuid>4ad3b2fc-2423-45b3-8355-ae890d6688d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-container']/div</value>
      <webElementGuid>651683fc-e21d-4736-b485-f364efe3038b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div</value>
      <webElementGuid>4e0a51b7-5f64-4d04-b480-acaa049549e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'hmenu-canvas-background']</value>
      <webElementGuid>b7d671d5-de8e-4c2e-a529-4b159bd7d6e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
