<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Amazon Launchpad</name>
   <tag></tag>
   <elementGuidId>3063d9c3-50fd-4e42-b666-aa0f039089e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-content']/ul/li[24]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(24) > a.hmenu-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>95493ecd-df87-4080-8dee-e24aa9ddda3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/gp/browse.html?node=10894223031&amp;ref_=nav_em_topnav_storetab_lpdin_0_1_1_27</value>
      <webElementGuid>fc7e8fec-40c9-41f0-b617-8f36e6be3346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmenu-item</value>
      <webElementGuid>de865705-2f5b-4f0f-802b-498d6a9a1d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amazon Launchpad</value>
      <webElementGuid>c4878602-49c1-46e5-a37b-3aae6e2f708b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-content&quot;)/ul[@class=&quot;hmenu hmenu-visible hmenu-translateX&quot;]/li[24]/a[@class=&quot;hmenu-item&quot;]</value>
      <webElementGuid>42922d32-35e6-493a-aa1a-0f9f9cfd89c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-content']/ul/li[24]/a</value>
      <webElementGuid>31c4ca4b-a5d8-41f7-bdc3-334411645fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Amazon Launchpad')]</value>
      <webElementGuid>6084f2fb-8fc7-46ff-8720-4ed66809b8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/gp/browse.html?node=10894223031&amp;ref_=nav_em_topnav_storetab_lpdin_0_1_1_27')]</value>
      <webElementGuid>269cf345-9865-49fb-bd91-c37c4a80c679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[24]/a</value>
      <webElementGuid>a3f5f07f-2b0d-4457-b5ce-44687f3f8057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/gp/browse.html?node=10894223031&amp;ref_=nav_em_topnav_storetab_lpdin_0_1_1_27' and (text() = 'Amazon Launchpad' or . = 'Amazon Launchpad')]</value>
      <webElementGuid>eb41e5d5-6f13-412e-af69-f435cbf12971</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
