<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_nav-sprite hmenu-arrow-prev</name>
   <tag></tag>
   <elementGuidId>f8361e11-3ccb-4e1d-867b-c619ab3efbf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-content']/ul[19]/li/a/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.hmenu.hmenu-visible.hmenu-translateX > li > a.hmenu-item.hmenu-back-button > div > i.nav-sprite.hmenu-arrow-prev</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>cc3a0c82-d536-46ee-9b47-fb48885fa519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-sprite hmenu-arrow-prev</value>
      <webElementGuid>d2e9e538-e886-4b80-8d42-6169884d9dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-content&quot;)/ul[@class=&quot;hmenu hmenu-visible hmenu-translateX&quot;]/li[1]/a[@class=&quot;hmenu-item hmenu-back-button&quot;]/div[1]/i[@class=&quot;nav-sprite hmenu-arrow-prev&quot;]</value>
      <webElementGuid>ebadd123-899d-4a43-a544-118cacaf2338</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-content']/ul[19]/li/a/div/i</value>
      <webElementGuid>cc89f785-738a-45d3-842d-270e795aecfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[19]/li/a/div/i</value>
      <webElementGuid>fb1bd44b-3888-40ef-bdca-16ce3397becb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
