<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Amazon Pay</name>
   <tag></tag>
   <elementGuidId>10c294ed-a934-43cb-965c-be5bdc9e8e00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-content']/ul/li[22]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(22) > a.hmenu-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3e66768c-059f-49a3-b4d8-e7b7d086ff06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/amazonpay/home?ref_=nav_em_apay_nav_desktop_0_1_1_25</value>
      <webElementGuid>0dbb30af-716f-4643-84d0-aebd3649c68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmenu-item</value>
      <webElementGuid>3847d26f-2806-43bd-88cf-98a141890c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Amazon Pay</value>
      <webElementGuid>8c399f0c-894c-4ad1-8e0b-bdf7689ddfdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-content&quot;)/ul[@class=&quot;hmenu hmenu-visible hmenu-translateX&quot;]/li[22]/a[@class=&quot;hmenu-item&quot;]</value>
      <webElementGuid>7db7ea4c-47aa-404c-9a26-35c5aa6ade2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-content']/ul/li[22]/a</value>
      <webElementGuid>74415353-5b6b-4ce0-9d4e-5aeb6bf020dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Amazon Pay')])[3]</value>
      <webElementGuid>28d3fab6-0e6f-4797-aa38-86d3faf517d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/amazonpay/home?ref_=nav_em_apay_nav_desktop_0_1_1_25')]</value>
      <webElementGuid>4e337416-ff1b-4f34-b9df-c1896551897a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[22]/a</value>
      <webElementGuid>c3193a93-d554-4516-9d25-24422df9ff35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/amazonpay/home?ref_=nav_em_apay_nav_desktop_0_1_1_25' and (text() = 'Amazon Pay' or . = 'Amazon Pay')]</value>
      <webElementGuid>61af5e9f-d24b-4e91-a6b6-98d2820eec7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
