<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Kindle E-Readers  eBooks</name>
   <tag></tag>
   <elementGuidId>c308def2-0f56-4d32-99b8-a790431a12ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-content']/ul/li[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(9) > a.hmenu-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a60a7f9c-db22-4eee-bf00-b8423b2f9341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmenu-item</value>
      <webElementGuid>bd88d95d-900c-4c27-a274-55b1dea61e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu-id</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>f881fe74-fe15-4f39-8cc4-05ce479885a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref-tag</name>
      <type>Main</type>
      <value>nav_em_1_1_1_8</value>
      <webElementGuid>e292636e-0dd3-45dc-b827-03cd2a931ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kindle E-Readers &amp; eBooks</value>
      <webElementGuid>04858766-40a0-42a6-89c1-b7cb283c126c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-content&quot;)/ul[@class=&quot;hmenu hmenu-visible hmenu-translateX&quot;]/li[9]/a[@class=&quot;hmenu-item&quot;]</value>
      <webElementGuid>b5f81366-9ce4-41aa-8924-cdfcbed51d19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-content']/ul/li[9]/a</value>
      <webElementGuid>5d02d4f8-e38e-4e91-802b-495cd9771013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[340]</value>
      <webElementGuid>de8538b2-d45e-4b49-9c69-fa90ffd03c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[9]/a</value>
      <webElementGuid>9d3ebd7f-25bc-4236-a910-c83fc002df17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Kindle E-Readers &amp; eBooks' or . = 'Kindle E-Readers &amp; eBooks')]</value>
      <webElementGuid>980a2ad6-bfff-4be4-8746-dd13ad550163</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
