<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_main menu</name>
   <tag></tag>
   <elementGuidId>76ca75b2-98f4-4997-918d-f3c2a7e53401</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-content']/ul[6]/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.hmenu.hmenu-visible.hmenu-translateX > li > a.hmenu-item.hmenu-back-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>435551ed-8624-468b-a9e2-1f8b5eb2a171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>0dcb7fe5-1e22-463f-81bf-0df0fab0fbdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmenu-item hmenu-back-button</value>
      <webElementGuid>54b4859a-e732-4207-9730-a3034cbbfcb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Back to main menu</value>
      <webElementGuid>9bbf4337-588d-476c-bd8f-5570c9117f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref-tag</name>
      <type>Main</type>
      <value>nav_em_1_6_BT_0_main_menu</value>
      <webElementGuid>4e9ada93-f474-4fcb-be3b-1ce9377938f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>main menu</value>
      <webElementGuid>8c249f5c-20c9-49d7-aea5-b467b0180122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-content&quot;)/ul[@class=&quot;hmenu hmenu-visible hmenu-translateX&quot;]/li[1]/a[@class=&quot;hmenu-item hmenu-back-button&quot;]</value>
      <webElementGuid>ff4e36b5-b2a4-4270-b81c-cfd73595a833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-content']/ul[6]/li/a</value>
      <webElementGuid>6cfc88f4-5d15-4fb8-9ee7-f08de6ffbeb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/')])[332]</value>
      <webElementGuid>539244fa-532e-4a21-b064-2bb7af841eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[6]/li/a</value>
      <webElementGuid>d846a37b-b0f8-47cc-bf21-ebb80da5b3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/' and (text() = 'main menu' or . = 'main menu')]</value>
      <webElementGuid>3a8e7ef3-fa0f-4ef2-88f0-cbca4a642c2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
