<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mobiles, Computers</name>
   <tag></tag>
   <elementGuidId>2c02ef0e-5e3e-4d9f-afe4-38e0110b593e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-content']/ul/li[15]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(15) > a.hmenu-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>837bb15f-ef37-45e7-a0ec-dad88b546687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmenu-item</value>
      <webElementGuid>1dd183dc-3c14-476a-8c6c-d6b27cf0ed00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu-id</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>b7e048e0-75c8-4658-ae8f-e7471482f95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref-tag</name>
      <type>Main</type>
      <value>nav_em_1_1_1_13</value>
      <webElementGuid>9bcfa923-9405-4adb-9dad-72c69be0f52d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mobiles, Computers</value>
      <webElementGuid>42e51086-8fca-4050-8d30-6143aa28c25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-content&quot;)/ul[@class=&quot;hmenu hmenu-visible hmenu-translateX&quot;]/li[15]/a[@class=&quot;hmenu-item&quot;]</value>
      <webElementGuid>51a00ece-bf4d-4faa-b691-4108e7d75975</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-content']/ul/li[15]/a</value>
      <webElementGuid>9d8e3e3c-e156-48d4-9d01-8b3fbb6599eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[344]</value>
      <webElementGuid>f8dcc2da-3125-4279-bae5-e19766bf584e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[15]/a</value>
      <webElementGuid>860a2a1e-8efc-46ca-8358-92ec1b3b8869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Mobiles, Computers' or . = 'Mobiles, Computers')]</value>
      <webElementGuid>ae238f48-a871-450e-b063-50d41c982422</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
