<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Womens Fashion</name>
   <tag></tag>
   <elementGuidId>72bab75c-7635-4d9a-9f6e-89970c1fd61f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-content']/ul/li[18]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(18) > a.hmenu-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8f4d778c-9f46-493e-87b5-4aa81ee5a6c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmenu-item</value>
      <webElementGuid>499609eb-c31c-426d-88df-5655b2d4096b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-menu-id</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>4d019edf-e968-4fa1-862b-3dd3e0d257db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref-tag</name>
      <type>Main</type>
      <value>nav_em_1_1_1_16</value>
      <webElementGuid>3f8d7c9d-8ca0-4670-b9b5-a718b3cd8f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Women's Fashion</value>
      <webElementGuid>73753923-6042-46b3-9d3e-c465b5e6f065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-content&quot;)/ul[@class=&quot;hmenu hmenu-visible hmenu-translateX&quot;]/li[18]/a[@class=&quot;hmenu-item&quot;]</value>
      <webElementGuid>58a36063-ac59-4e45-855d-ee4103e9dbcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-content']/ul/li[18]/a</value>
      <webElementGuid>edae0359-7027-4997-beaf-5cb83dfee5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[347]</value>
      <webElementGuid>4dfc2495-982e-409c-8268-2baf88100fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[18]/a</value>
      <webElementGuid>4703dbd9-6463-40ab-a010-65ffd6fdf7f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = concat(&quot;Women&quot; , &quot;'&quot; , &quot;s Fashion&quot;) or . = concat(&quot;Women&quot; , &quot;'&quot; , &quot;s Fashion&quot;))]</value>
      <webElementGuid>f232127e-a3a7-4f3b-bcbd-faebb7470e40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
