<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_nav-sprite hmenu-arrow-prev</name>
   <tag></tag>
   <elementGuidId>e8431fb2-4c55-45fa-9c47-5092ebbcf74b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmenu-content']/ul[2]/li/a/div/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.nav-sprite.hmenu-arrow-prev</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>80b3cb41-c597-4b3d-a294-cd4b81929b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-sprite hmenu-arrow-prev</value>
      <webElementGuid>0b3b0e91-58b3-44b6-aa9a-666f4732493a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmenu-content&quot;)/ul[@class=&quot;hmenu hmenu-visible hmenu-translateX&quot;]/li[1]/a[@class=&quot;hmenu-item hmenu-back-button&quot;]/div[1]/i[@class=&quot;nav-sprite hmenu-arrow-prev&quot;]</value>
      <webElementGuid>0c83bae3-c1dc-444b-9e8d-c243fb15218a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmenu-content']/ul[2]/li/a/div/i</value>
      <webElementGuid>f57238c5-806d-4ddc-b96c-d5aa29966a30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/i</value>
      <webElementGuid>ebf38ee4-3618-4efd-b297-bbf756a380eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
